package com.ven.assists.web.filesystem

/**
 * 路径相关的方法常量定义
 */
object PathCallMethod {
    const val pathJoin = "pathJoin"
    const val getRootPath = "getRootPath"
    const val getDataPath = "getDataPath"
    const val getDownloadCachePath = "getDownloadCachePath"
    const val getInternalAppDataPath = "getInternalAppDataPath"
    const val getInternalAppCodeCacheDir = "getInternalAppCodeCacheDir"
    const val getInternalAppCachePath = "getInternalAppCachePath"
    const val getInternalAppDbsPath = "getInternalAppDbsPath"
    const val getInternalAppDbPath = "getInternalAppDbPath"
    const val getInternalAppFilesPath = "getInternalAppFilesPath"
    const val getInternalAppSpPath = "getInternalAppSpPath"
    const val getInternalAppNoBackupFilesPath = "getInternalAppNoBackupFilesPath"
    const val getExternalStoragePath = "getExternalStoragePath"
    const val getExternalMusicPath = "getExternalMusicPath"
    const val getExternalPodcastsPath = "getExternalPodcastsPath"
    const val getExternalRingtonesPath = "getExternalRingtonesPath"
    const val getExternalAlarmsPath = "getExternalAlarmsPath"
    const val getExternalNotificationsPath = "getExternalNotificationsPath"
    const val getExternalPicturesPath = "getExternalPicturesPath"
    const val getExternalMoviesPath = "getExternalMoviesPath"
    const val getExternalDownloadsPath = "getExternalDownloadsPath"
    const val getExternalDcimPath = "getExternalDcimPath"
    const val getExternalDocumentsPath = "getExternalDocumentsPath"
    const val getExternalAppDataPath = "getExternalAppDataPath"
    const val getExternalAppCachePath = "getExternalAppCachePath"
    const val getExternalAppFilesPath = "getExternalAppFilesPath"
    const val getExternalAppMusicPath = "getExternalAppMusicPath"
    const val getExternalAppPodcastsPath = "getExternalAppPodcastsPath"
    const val getExternalAppRingtonesPath = "getExternalAppRingtonesPath"
    const val getExternalAppAlarmsPath = "getExternalAppAlarmsPath"
    const val getExternalAppNotificationsPath = "getExternalAppNotificationsPath"
    const val getExternalAppPicturesPath = "getExternalAppPicturesPath"
    const val getExternalAppMoviesPath = "getExternalAppMoviesPath"
    const val getExternalAppDownloadPath = "getExternalAppDownloadPath"
    const val getExternalAppDcimPath = "getExternalAppDcimPath"
    const val getExternalAppDocumentsPath = "getExternalAppDocumentsPath"
    const val getExternalAppObbPath = "getExternalAppObbPath"
    const val getRootPathExternalFirst = "getRootPathExternalFirst"
    const val getAppDataPathExternalFirst = "getAppDataPathExternalFirst"
    const val getFilesPathExternalFirst = "getFilesPathExternalFirst"
    const val getCachePathExternalFirst = "getCachePathExternalFirst"
}

